---
apiVersion: v1
kind: Pod
metadata:
  name: OAM-10-3-0
spec:
  containers:
      - name: oam-8-3-0 # Main container
         image: nginx # Use the nginx image
         resources:
            requests:
               memory: "1064Mi"
               cpu: "8"
            limits:
               memory: "1064Mi"
               cpu: "8"
         ports:
						  - containerPort: 80 # Expose port 80
         command: ["/bin/sh"] # Override the default command
         args: ["-c", "while true; do echo \"$(date) Hello from nginx\"; sleep 1; done | tee /var/log/nginx/access.log"]
     - name: oam-sc-8-3-0 # # Sidecar container
         image: alpine/socat # Use the alpine/socat image
         resources:
            requests:
               memory: "64Mi"
               cpu: "2"
            limits:
               memory: "64Mi"
               cpu: "2"
         ports:
						  - containerPort: 8080 # Expose port 8080
         command: ["socat"] # Override the default command
         args: ["-v", "TCP-LISTEN:8080,fork,reuseaddr", "EXEC:\"kubectl logs web-server-7f9f8c4b9-6xq8w -c nginx\""]
